# Project 1

# Calculating the Minimum dietary energy requirement (kcal/cap/day) for different countries in 2022

- Step 1: Display the dataset (should have atleast 1000 rows)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dietry_req.csv")
df

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2017,2017,kcal/cap/d,1650,E,Estimated value,NaN
1,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2018,2018,kcal/cap/d,1652,E,Estimated value,NaN
2,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2019,2019,kcal/cap/d,1656,E,Estimated value,NaN
3,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2020,2020,kcal/cap/d,1659,E,Estimated value,NaN
4,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2021,2021,kcal/cap/d,1662,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2018,2018,kcal/cap/d,1736,E,Estimated value,NaN
1154,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2019,2019,kcal/cap/d,1740,E,Estimated value,NaN
1155,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2020,2020,kcal/cap/d,1743,E,Estimated value,NaN
1156,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2021,2021,kcal/cap/d,1747,E,Estimated value,NaN
1157,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1752,E,Estimated value,NaN

- Step 2: Filter the dataset to only compute the dietary requirements for all countries for the year 2022

In [3]:
df_2022 = df[df['Year Code'] == 2022]
df_2022

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
5,FS,Suite of Food Security Indicators,4,Afghanistan,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1664,E,Estimated value,NaN
11,FS,Suite of Food Security Indicators,8,Albania,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1916,E,Estimated value,NaN
17,FS,Suite of Food Security Indicators,12,Algeria,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1787,E,Estimated value,NaN
23,FS,Suite of Food Security Indicators,24,Angola,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1672,E,Estimated value,NaN
29,FS,Suite of Food Security Indicators,28,Antigua and Barbuda,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1910,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1133,FS,Suite of Food Security Indicators,862,Venezuela (Bolivarian Republic of),6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1821,E,Estimated value,NaN
1139,FS,Suite of Food Security Indicators,704,Viet Nam,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1788,E,Estimated value,NaN
1145,FS,Suite of Food Security Indicators,887,Yemen,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1708,E,Estimated value,NaN
1151,FS,Suite of Food Security Indicators,894,Zambia,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1715,E,Estimated value,NaN
1157,FS,Suite of Food Security Indicators,716,Zimbabwe,6128,Value,21056,Minimum dietary energy requirement (kcal/cap/...,2022,2022,kcal/cap/d,1752,E,Estimated value,NaN

- Step 3: Find the Mean, Median and Mode using pandas

In [4]:
mean_value = df_2022['Value'].mean()
median_value = df_2022['Value'].median()
mode_value = df_2022['Value'].mode()[0]

print(f"Mean of the minimum dietary energy requirement is: {mean_value:.2f}(kcal/cap/day)")
print(f"Median of the minimum dietary energy requirement is: {median_value}(kcal/cap/day)")
print(f"Mode of the minimum dietary energy requirement is: {mode_value}(kcal/cap/day)")

Mean of the minimum dietary energy requirement is: 1838.69(kcal/cap/day)
Median of the minimum dietary energy requirement is: 1841.0(kcal/cap/day)
Mode of the minimum dietary energy requirement is: 1737(kcal/cap/day)

- Step 4: Find the Mean, Median, Mode without pandas

In [5]:
import csv
from statistics import mean, median, mode

In [6]:
with open('dietry_req.csv', 'r') as file:
    reader = csv.DictReader(file)
    data_2022 = [float(row ['Value'])
                 for row in reader if row['Year'] == '2022']

In [7]:
mean_value = mean(data_2022)
median_value = median(data_2022)
mode_value = mode(data_2022)

print(f"Mean of the minimum dietary energy requirement is: {mean_value:.2f}(kcal/cap/day)")
print(f"Median of the minimum dietary energy requirement is: {median_value}(kcal/cap/day)")
print(f"Mode of the minimum dietary energy requirement is: {mode_value}(kcal/cap/day)")

Mean of the minimum dietary energy requirement is: 1838.69(kcal/cap/day)
Median of the minimum dietary energy requirement is: 1841.0(kcal/cap/day)
Mode of the minimum dietary energy requirement is: 1737.0(kcal/cap/day)

- Step 5: Data Visualization

In [8]:
import csv
from statistics import mean, median, mode

In [9]:
with open('dietry_req.csv', 'r') as file:
    reader = csv.DictReader(file)
    data_2022 = [
        (row['Area'], float(row['Value']))
        for row in reader if row['Year'] == '2022'
        ]

In [10]:
values = [value for _, value in data_2022]
mean_value = mean(values)
median_value = median(values)
mode_value = mode(values)

print(f"Mean: {mean_value:.2f}")
print(f"Median: {median_value:.2f}")
print(f"Mode: {mode_value:.2f}")

Mean: 1838.69
Median: 1841.00
Mode: 1737.00

In [11]:
print("\nMinimum Dietary Energy Requirement (kcal/cap/day) for 2022")
max_value = max(values)
bar_width = 50 


for country, value in data_2022:
    bar_length = int((value / max_value) * bar_width)
    bar = '*' * bar_length
    print(f"{country}: {bar} {value:.2f}")

Minimum Dietary Energy Requirement (kcal/cap/day) for 2022
Afghanistan: *************************************** 1664.00
Albania: ********************************************* 1916.00
Algeria: ****************************************** 1787.00
Angola: *************************************** 1672.00
Antigua and Barbuda: ********************************************* 1910.00
Argentina: ******************************************** 1884.00
Armenia: ******************************************** 1872.00
Australia: ********************************************* 1922.00
Austria: ********************************************** 1948.00
Azerbaijan: ******************************************** 1877.00
Bahamas: ********************************************** 1931.00
Bahrain: ********************************************** 1934.00
Bangladesh: ****************************************** 1790.00
Barbados: ********************************************* 1920.00
Belarus: ********************************************* 1899.00
Belgium: ********************************************** 1956.00
Belize: ****************************************** 1787.00
Benin: **************************************** 1720.00
Bermuda: *********************************************** 2013.00
Bhutan: ******************************************* 1841.00
Bolivia (Plurinational State of): ****************************************** 1767.00
Bosnia and Herzegovina: ********************************************* 1927.00
Botswana: ******************************************* 1827.00
Brazil: ********************************************* 1894.00
Brunei Darussalam: ******************************************** 1872.00
Bulgaria: ********************************************* 1921.00
Burkina Faso: ***************************************** 1737.00
Burundi: *************************************** 1667.00
Cabo Verde: ******************************************** 1874.00
Cambodia: ****************************************** 1784.00
Cameroon: ***************************************** 1749.00
Canada: ********************************************* 1926.00
Central African Republic: *************************************** 1661.00
Chad: **************************************** 1699.00
Chile: ********************************************* 1891.00
China: ********************************************* 1894.00
China, Hong Kong SAR: ******************************************** 1879.00
China, Macao SAR: ******************************************** 1880.00
China, mainland: ********************************************* 1894.00
China, Taiwan Province of: ********************************************* 1904.00
Colombia: ******************************************* 1833.00
Comoros: ***************************************** 1749.00
Congo: ***************************************** 1747.00
Costa Rica: ********************************************* 1892.00
CÃ´te d'Ivoire: ***************************************** 1737.00
Croatia: ********************************************* 1920.00
Cuba: ********************************************* 1890.00
Cyprus: ********************************************** 1950.00
Czechia: ********************************************** 1947.00
Democratic People's Republic of Korea: ******************************************** 1861.00
Democratic Republic of the Congo: *************************************** 1654.00
Denmark: ********************************************** 1957.00
Djibouti: ******************************************* 1846.00
Dominica: ************************************************** 2098.00
Dominican Republic: ******************************************** 1854.00
Ecuador: ****************************************** 1799.00
Egypt: ******************************************* 1820.00
El Salvador: ****************************************** 1791.00
Equatorial Guinea: ****************************************** 1779.00
Eritrea: ***************************************** 1744.00
Estonia: ********************************************** 1956.00
Eswatini: ****************************************** 1801.00
Ethiopia: ***************************************** 1737.00
Fiji: ******************************************* 1836.00
Finland: ********************************************** 1967.00
France: ********************************************* 1924.00
French Polynesia: ******************************************** 1880.00
Gabon: ****************************************** 1785.00
Gambia: ***************************************** 1760.00
Georgia: ********************************************* 1893.00
Germany: ********************************************** 1947.00
Ghana: ****************************************** 1785.00
Greece: ********************************************** 1940.00
Grenada: ********************************************* 1911.00
Guatemala: ***************************************** 1723.00
Guinea: ***************************************** 1730.00
Guinea-Bissau: ***************************************** 1749.00
Guyana: ****************************************** 1796.00
Haiti: ******************************************* 1822.00
Honduras: ****************************************** 1787.00
Hungary: ********************************************** 1947.00
Iceland: ********************************************** 1967.00
India: ****************************************** 1803.00
Indonesia: ****************************************** 1794.00
Iran (Islamic Republic of): ******************************************** 1847.00
Iraq: ****************************************** 1778.00
Ireland: ********************************************* 1921.00
Israel: ****************************************** 1783.00
Italy: ********************************************** 1946.00
Jamaica: ********************************************** 1931.00
Japan: ******************************************** 1869.00
Jordan: ******************************************* 1829.00
Kazakhstan: ******************************************* 1815.00
Kenya: ***************************************** 1756.00
Kiribati: ***************************************** 1746.00
Kuwait: ********************************************* 1916.00
Kyrgyzstan: ****************************************** 1798.00
Lao People's Democratic Republic: ******************************************* 1825.00
Latvia: ********************************************* 1895.00
Lebanon: ******************************************* 1831.00
Lesotho: ****************************************** 1782.00
Liberia: ***************************************** 1727.00
Libya: ******************************************** 1852.00
Lithuania: ********************************************* 1898.00
Luxembourg: *********************************************** 1988.00
Madagascar: **************************************** 1707.00
Malawi: **************************************** 1704.00
Malaysia: ******************************************** 1850.00
Maldives: ******************************************** 1869.00
Mali: **************************************** 1712.00
Malta: *********************************************** 1973.00
Mauritania: ***************************************** 1758.00
Mauritius: ******************************************** 1885.00
Mexico: ******************************************** 1859.00
Micronesia (Federated States of): ****************************************** 1780.00
Mongolia: ****************************************** 1791.00
Montenegro: ********************************************* 1905.00
Morocco: ******************************************** 1847.00
Mozambique: **************************************** 1689.00
Myanmar: ****************************************** 1802.00
Namibia: ****************************************** 1794.00
Nepal: ***************************************** 1762.00
Netherlands (Kingdom of the): *********************************************** 1979.00
New Caledonia: ******************************************* 1812.00
New Zealand: ********************************************* 1922.00
Nicaragua: ****************************************** 1787.00
Niger: *************************************** 1671.00
Nigeria: **************************************** 1716.00
North Macedonia: ********************************************** 1935.00
Norway: ********************************************** 1965.00
Oman: ******************************************** 1874.00
Pakistan: ***************************************** 1737.00
Palestine: ***************************************** 1732.00
Panama: ****************************************** 1792.00
Papua New Guinea: ***************************************** 1737.00
Paraguay: ******************************************* 1830.00
Peru: ****************************************** 1792.00
Philippines: ***************************************** 1750.00
Poland: ********************************************** 1935.00
Portugal: ********************************************* 1920.00
Puerto Rico: ********************************************* 1919.00
Qatar: ************************************************ 2027.00
Republic of Korea: ********************************************* 1904.00
Republic of Moldova: ********************************************* 1905.00
Romania: ********************************************* 1918.00
Russian Federation: ********************************************* 1909.00
Rwanda: ***************************************** 1737.00
Saint Lucia: ********************************************** 1932.00
Saint Vincent and the Grenadines: ********************************************* 1914.00
Samoa: ******************************************* 1818.00
Sao Tome and Principe: ****************************************** 1769.00
Saudi Arabia: ******************************************** 1869.00
Senegal: ****************************************** 1767.00
Serbia: ********************************************* 1920.00
Seychelles: ******************************************** 1868.00
Sierra Leone: ***************************************** 1750.00
Singapore: ********************************************* 1912.00
Slovakia: ********************************************** 1955.00
Slovenia: ********************************************* 1924.00
Solomon Islands: **************************************** 1706.00
Somalia: **************************************** 1700.00
South Africa: ******************************************* 1836.00
South Sudan: ***************************************** 1723.00
Spain: ********************************************** 1934.00
Sri Lanka: ****************************************** 1794.00
Sudan: ***************************************** 1725.00
Suriname: ******************************************** 1849.00
Sweden: ********************************************** 1951.00
Switzerland: ********************************************** 1966.00
Syrian Arab Republic: ******************************************* 1831.00
Tajikistan: ****************************************** 1777.00
Thailand: ********************************************* 1889.00
Timor-Leste: ***************************************** 1729.00
Togo: ***************************************** 1751.00
Tonga: ********************************************* 1902.00
Trinidad and Tobago: ******************************************** 1885.00
Tunisia: ******************************************* 1820.00
TÃ¼rkiye: ******************************************** 1867.00
Turkmenistan: ****************************************** 1791.00
Uganda: **************************************** 1714.00
Ukraine: ********************************************* 1921.00
United Arab Emirates: ************************************************ 2038.00
United Kingdom of Great Britain and Northern Ireland: ********************************************* 1922.00
United Republic of Tanzania: *************************************** 1678.00
United States of America: ********************************************** 1966.00
Uruguay: ******************************************** 1883.00
Uzbekistan: ******************************************* 1825.00
Vanuatu: **************************************** 1690.00
Venezuela (Bolivarian Republic of): ******************************************* 1821.00
Viet Nam: ****************************************** 1788.00
Yemen: **************************************** 1708.00
Zambia: **************************************** 1715.00
Zimbabwe: ***************************************** 1752.00